version: '3.3'

services:
  csa:
    container_name: csa
    volumes:
      - .:/app/
      - /app/node_modules
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - ${PORT}:3000
