export enum INTERNE_RULES {
  RULE_FIRSTNAME_LENGTH = "rule::firstname::length",
  RULE_LASTNAME_LENGTH = "rule::lastname::length",
  RULE_ALPHA_RATE = 2,
  RULE_NUMBER_RATE = 3,
}

export enum QUOTATION_SERVICE_RULE {
  RULE_PRICE_QUOTATION_RATE = 0
}

export enum BLACKLIST_SERVICE_RULE {
  RULE_REGISTERNUMBER_BLACKLIST = 0
}
